### ISSUE TITLE
添加base64字符串图片提示访问失败

### ISSUE THREAD

**Issue by JackA1ltman** [nlbwqmz/wj-markdown-editor#10]
如图，无法正常显示
系统：Arch Linux
![屏幕截图_20241115_105100](https://github.com/user-attachments/assets/0b19f6f4-c835-40e7-9ae5-855c71727df2)
这里是正常的样子
![屏幕截图_20241115_105128](https://github.com/user-attachments/assets/fb3f463b-4276-430a-83fb-02be287bb18e)

**Comment by nlbwqmz** [comment]
base64图片可以直接用img标签:`<img src="base64"/>`
