### ISSUE TITLE
【增强】webdav登录信息不能保存

### ISSUE THREAD

**Issue by ghost** [nlbwqmz/wj-markdown-editor#3]
两个问题：
1、webdav登录信息不能保存。打开软件登录webdav，正常。关闭软件后再打开，需要重新登录webdav。
2、文档采用webdav方式保存正常，但是如果下一个文档改为本地保存，就再也回不到webdav保存了，保存到webdav选项为灰色
![image](https://github.com/nlbwqmz/wj-markdown-editor/assets/26591015/bc1ab8f8-6e3a-47e9-acb4-4c0500329bdf)

**Comment by nlbwqmz** [comment]
第一个问题：后续会支持保存登录状态。
第二个问题：新文件保存到webdav时，需要在输入框中输入文件名称，后续会加强提示。

**Comment by nlbwqmz** [comment]
v1.1.0 已优化
