### ISSUE TITLE
小小建议

### ISSUE THREAD

**Issue by tongnixcv** [nlbwqmz/wj-markdown-editor#4]
非常喜欢您的作品，打算作为主力写作软件
不过建议图标可以再优化下，有些场景图标显示可能会有些问题

![Clip_20240329_155221](https://github.com/nlbwqmz/wj-markdown-editor/assets/44078465/d0559f01-cbe2-4617-b65a-e078eeed65d2)
![未命名-1](https://github.com/nlbwqmz/wj-markdown-editor/assets/44078465/031bbb01-a351-47bb-9282-e2b1ccb3bd9c)

**Comment by nlbwqmz** [comment]
根据您的描述没有发现哪里出现了问题，可以再详细说明下吗？

**Comment by tongnixcv** [comment]
> 我发现问题了，图标颜色和背景色相近的时候会出现问题，后续会调整图标。

是的，这可能是单色图标的问题

**Comment by nlbwqmz** [comment]
v1.1.0 已优化
