### ISSUE TITLE
桌面端的界面大小不可以拖动设置大小，希望作者可以看看

### ISSUE THREAD

**Issue by zhang1446802857** [nlbwqmz/wj-markdown-editor#5]
桌面端的界面大小不可以拖动设置大小，希望作者可以看看。
就是只能最大化，不能自己根据窗口去拖动设置大小，虽然放上去有拖动的箭头，但是没效果

**Comment by nlbwqmz** [comment]
目前程序为了布局显示不错乱，限制了最小宽度为850像素，最小高度为280像素，大于该尺寸都没问题。
![GIF 2024-04-07 14-31-51](https://github.com/nlbwqmz/wj-markdown-editor/assets/43941671/0bac4b57-8cbb-497c-a757-b589474def53)

**Comment by nlbwqmz** [comment]
你是想要缩小到更小的尺寸吗？你可以先试下，拖动放大尺寸有没有问题，没问题的话，我可以把这个限制放开。

**Comment by zhang1446802857** [comment]
你好。我觉得可能是我不是最新版本的问题，刚才我更新到最新版本可以了。

顺便想问问，能不能打开软件的时候可以记住上次打开的文件呢，这样我就不用去文件夹里一层层的去找了。

**Comment by nlbwqmz** [comment]
后续会加上该功能。

**Comment by zhang1446802857** [comment]
爱你

**Comment by nlbwqmz** [comment]
已在v1.2.1版本中增强。

**Comment by zhang1446802857** [comment]
爱你爱你
